# Generated by Django 4.2.7 on 2025-08-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boxoffice", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metrics",
            name="total_booked_seats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="metrics",
            name="total_expired_seats",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="metrics",
            name="total_held_seats",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
